version: "3"
services:
  arkserver1:
    image: midnightsfx/arkswarm:v0.2.26
    volumes:
        - /servers/cluster_ark/ARK_Valguero:/server
    environment:
      serverMap: "Valguero_P" # required
      ark_SessionName: "ARK-Server"
      ark_Port: 7778
      ark_QueryPort: 27015
      ark_RCONPort: 32330
      ark_MaxPlayers: 15
    ports:
        - 7778:7778/udp
        - 7778:7778
        - 27015:27015/udp
        - 27015:27015
        - 32330:32330


  